package preview

import (
	"bytes"
	"fmt"
	"image"
	"image/color"
	"image/draw"
	"image/png"
	"math"
	"sort"
	"strconv"
	"strings"
	"sync"
	"time"
	"unicode/utf8"

	"github.com/Veyal/interseptor/internal/rendermark"
	"golang.org/x/image/font"
	"golang.org/x/image/font/gofont/gobold"
	"golang.org/x/image/font/gofont/gomono"
	"golang.org/x/image/font/gofont/goregular"
	"golang.org/x/image/font/opentype"
	"golang.org/x/image/math/fixed"
)

func pow(x, y float64) float64 { return math.Pow(x, y) }

// FooterText is the mandatory provenance line drawn on every evidence render.
const FooterText = "Generated by Interseptor from recorded data - not a browser screenshot"

const (
	badgeText = "Generated evidence render"
	brandText = "Interseptor"
	titleH    = 40
	footerH   = 44
	frameGut  = 20
)

type fontKind int

const (
	fontSans fontKind = iota
	fontBold
	fontMono
)

type faceKey struct {
	kind fontKind
	size int
}

var fontData = map[fontKind][]byte{fontSans: goregular.TTF, fontBold: gobold.TTF, fontMono: gomono.TTF}

// Parsed fonts are cached behind a mutex. Faces hold glyph caches and are not
// safe for concurrent use, so each canvas builds its own faces from them.
var (
	parsedMu sync.Mutex
	parsed   = map[fontKind]*opentype.Font{}
)

func newFace(kind fontKind, size int) font.Face {
	parsedMu.Lock()
	f := parsed[kind]
	if f == nil {
		var err error
		f, err = opentype.Parse(fontData[kind])
		if err != nil {
			parsedMu.Unlock()
			panic(fmt.Sprintf("preview: embedded font: %v", err))
		}
		parsed[kind] = f
	}
	parsedMu.Unlock()
	face, err := opentype.NewFace(f, &opentype.FaceOptions{Size: float64(size), DPI: 72, Hinting: font.HintingFull})
	if err != nil {
		panic(fmt.Sprintf("preview: face: %v", err))
	}
	return face
}

// canvas wraps an RGBA image with a palette and per-canvas font faces.
type canvas struct {
	img   *image.RGBA
	pal   reportPalette
	faces map[faceKey]font.Face
	// escaped records that a rune the embedded fonts cannot draw was replaced
	// by a readable U+XXXX escape; renderFrame then says so in the footer.
	escaped bool
	glyphs  map[glyphKey]bool
}

type glyphKey struct {
	kind fontKind
	r    rune
}

// escapedFooterNote is appended to the footer when any text was escaped.
const escapedFooterNote = "Characters outside the embedded font are shown as U+XXXX."

func newCanvas(w, h int, pal reportPalette) *canvas {
	c := &canvas{img: image.NewRGBA(image.Rect(0, 0, w, h)), pal: pal, faces: map[faceKey]font.Face{}, glyphs: map[glyphKey]bool{}}
	c.fill(pal.paper)
	return c
}

func (c *canvas) face(kind fontKind, size int) font.Face {
	k := faceKey{kind, size}
	f := c.faces[k]
	if f == nil {
		f = newFace(kind, size)
		c.faces[k] = f
	}
	return f
}

func (c *canvas) close() {
	for _, f := range c.faces {
		_ = f.Close()
	}
}

func (c *canvas) fill(col color.RGBA) {
	draw.Draw(c.img, c.img.Bounds(), image.NewUniform(col), image.Point{}, draw.Src)
}

func (c *canvas) rect(x, y, w, h int, col color.RGBA) {
	if w <= 0 || h <= 0 {
		return
	}
	r := image.Rect(x, y, x+w, y+h).Intersect(c.img.Bounds())
	if r.Empty() {
		return
	}
	draw.Draw(c.img, r, image.NewUniform(col), image.Point{}, draw.Src)
}

func (c *canvas) strokeRect(x, y, w, h int, col color.RGBA) {
	c.rect(x, y, w, 1, col)
	c.rect(x, y+h-1, w, 1, col)
	c.rect(x, y, 1, h, col)
	c.rect(x+w-1, y, 1, h, col)
}

func (c *canvas) set(x, y int, col color.RGBA) {
	if image.Pt(x, y).In(c.img.Bounds()) {
		c.img.SetRGBA(x, y, col)
	}
}

// line draws a 1px Bresenham line.
func (c *canvas) line(x0, y0, x1, y1 int, col color.RGBA) {
	dx, dy := absInt(x1-x0), -absInt(y1-y0)
	sx, sy := 1, 1
	if x0 > x1 {
		sx = -1
	}
	if y0 > y1 {
		sy = -1
	}
	err := dx + dy
	for {
		c.set(x0, y0, col)
		if x0 == x1 && y0 == y1 {
			return
		}
		e2 := 2 * err
		if e2 >= dy {
			err += dy
			x0 += sx
		}
		if e2 <= dx {
			err += dx
			y0 += sy
		}
	}
}

// arrow draws a line with a filled head at (x1,y1).
func (c *canvas) arrow(x0, y0, x1, y1 int, col color.RGBA) {
	c.line(x0, y0, x1, y1, col)
	ang := math.Atan2(float64(y1-y0), float64(x1-x0))
	const hl = 8.0
	for _, d := range []float64{0.45, -0.45} {
		hx := x1 - int(math.Round(hl*math.Cos(ang+d)))
		hy := y1 - int(math.Round(hl*math.Sin(ang+d)))
		c.line(x1, y1, hx, hy, col)
	}
}

func absInt(v int) int {
	if v < 0 {
		return -v
	}
	return v
}

// hasGlyph reports whether the embedded face can draw r.
func (c *canvas) hasGlyph(kind fontKind, size int, r rune) bool {
	k := glyphKey{kind, r}
	if ok, hit := c.glyphs[k]; hit {
		return ok
	}
	_, ok := c.face(kind, size).GlyphAdvance(r)
	c.glyphs[k] = ok
	return ok
}

// sanitize makes s drawable: control characters become spaces and runes the
// embedded fonts lack (CJK and other non-Latin scripts) become U+XXXX, so
// distinct payloads stay distinguishable instead of drawing as identical tofu.
func (c *canvas) sanitize(kind fontKind, size int, s string) string {
	clean := true
	for i := 0; i < len(s); i++ {
		if s[i] >= 0x80 || s[i] < 0x20 || s[i] == 0x7f {
			clean = false
			break
		}
	}
	if clean {
		return s
	}
	var b strings.Builder
	for _, r := range s {
		switch {
		case r == utf8.RuneError || r < 0x20 || r == 0x7f:
			b.WriteByte(' ')
		case r < 0x80 || c.hasGlyph(kind, size, r):
			b.WriteRune(r)
		default:
			c.escaped = true
			b.WriteString("U+" + strings.ToUpper(strconv.FormatInt(int64(r), 16)))
		}
	}
	return b.String()
}

// measure returns the pixel width of s as drawn.
func (c *canvas) measure(kind fontKind, size int, s string) int {
	return font.MeasureString(c.face(kind, size), c.sanitize(kind, size, s)).Ceil()
}

// text draws s with its top-left at (x,y) and returns the width drawn.
func (c *canvas) text(x, y int, s string, kind fontKind, size int, col color.RGBA) int {
	f := c.face(kind, size)
	d := &font.Drawer{Dst: c.img, Src: image.NewUniform(col), Face: f,
		Dot: fixed.P(x, y+f.Metrics().Ascent.Ceil())}
	d.DrawString(c.sanitize(kind, size, s))
	return d.Dot.X.Ceil() - x
}

// textRight draws s ending at right edge xr.
func (c *canvas) textRight(xr, y int, s string, kind fontKind, size int, col color.RGBA) {
	c.text(xr-c.measure(kind, size, s), y, s, kind, size, col)
}

func (c *canvas) lineH(kind fontKind, size int) int {
	return c.face(kind, size).Metrics().Height.Ceil() + 2
}

// maxRunesFor bounds how many runes of untrusted text can ever matter for a
// maxW pixel budget (every drawn rune is at least about one pixel wide).
func maxRunesFor(maxW int) int {
	if maxW < 16 {
		return 16
	}
	return maxW + 8
}

// clipRunes returns the first n runes of s and whether anything was cut.
func clipRunes(s string, n int) (string, bool) {
	if len(s) <= n {
		return s, false
	}
	i := 0
	for count := 0; count < n; count++ {
		if i >= len(s) {
			return s, false
		}
		_, w := utf8.DecodeRuneInString(s[i:])
		i += w
	}
	if i >= len(s) {
		return s, false
	}
	return s[:i], true
}

// fitPrefix returns the largest rune count n in [0,len(r)] with
// measure(prefix(n)+suffix) <= maxW, found by binary search.
func (c *canvas) fitPrefix(kind fontKind, size int, r []rune, suffix string, maxW int) int {
	return sort.Search(len(r), func(i int) bool {
		return c.measure(kind, size, strings.TrimRight(string(r[:i+1]), " ")+suffix) > maxW
	})
}

// truncate shortens s with an ellipsis so it fits maxW pixels. It is linear in
// the clipped input and logarithmic in measurements, so hostile megabyte
// strings stay cheap.
func (c *canvas) truncate(kind fontKind, size int, s string, maxW int) string {
	if maxW <= 0 {
		return ""
	}
	s, clipped := clipRunes(s, maxRunesFor(maxW))
	if !clipped && c.measure(kind, size, s) <= maxW {
		return s
	}
	const ell = "..."
	r := []rune(s)
	if n := c.fitPrefix(kind, size, r, ell, maxW); n > 0 {
		return strings.TrimRight(string(r[:n]), " ") + ell
	}
	if c.measure(kind, size, ell) <= maxW {
		return ell
	}
	return ""
}

// truncateMiddle shortens s to maxW pixels by eliding its middle ("iden...min"),
// keeping both the distinguishing start and end of identifiers.
func (c *canvas) truncateMiddle(kind fontKind, size int, s string, maxW int) string {
	if maxW <= 0 {
		return ""
	}
	s, clipped := clipRunes(s, maxRunesFor(maxW))
	if !clipped && c.measure(kind, size, s) <= maxW {
		return s
	}
	const ell = "..."
	r := []rune(s)
	mid := func(k int) string {
		if k > len(r)/2 {
			k = len(r) / 2
		}
		return string(r[:k]) + ell + string(r[len(r)-k:])
	}
	k := sort.Search(len(r)/2, func(i int) bool { return c.measure(kind, size, mid(i+1)) > maxW })
	if k == 0 {
		return c.truncate(kind, size, s, maxW)
	}
	return mid(k)
}

// wrap breaks s into lines of at most maxW pixels, hard-splitting long words.
// At most maxLines lines are returned (<=0 means unlimited); the last is
// ellipsised when text remains. Input is clipped to what could be shown.
func (c *canvas) wrap(kind fontKind, size int, s string, maxW, maxLines int) []string {
	budget := 4096
	if maxLines > 0 && maxW > 0 {
		budget = maxLines*(maxRunesFor(maxW)) + 8
	}
	s, _ = clipRunes(s, budget)
	var lines []string
	cur := ""
	flush := func() {
		lines = append(lines, cur)
		cur = ""
	}
	for _, w := range strings.Fields(s) {
		for maxW > 0 && c.measure(kind, size, w) > maxW {
			r := []rune(w)
			n := c.fitPrefix(kind, size, r, "", maxW)
			if n < 1 {
				n = 1
			}
			if cur != "" {
				flush()
			}
			cur = string(r[:n])
			w = string(r[n:])
			flush()
			if maxLines > 0 && len(lines) > maxLines {
				break
			}
		}
		if w == "" {
			continue
		}
		try := w
		if cur != "" {
			try = cur + " " + w
		}
		if c.measure(kind, size, try) > maxW && cur != "" {
			flush()
			cur = w
		} else {
			cur = try
		}
		if maxLines > 0 && len(lines) > maxLines {
			break
		}
	}
	if cur != "" {
		flush()
	}
	if maxLines > 0 && len(lines) > maxLines {
		lines = lines[:maxLines]
		lines[maxLines-1] = c.truncate(kind, size, lines[maxLines-1]+"...", maxW)
	}
	return lines
}

// formatTick prints an axis tick rounded to the precision of step so float
// noise such as 0.6000000000000001 never reaches the image.
func formatTick(v, step float64) string {
	dec := 0
	if step > 0 {
		dec = int(math.Ceil(-math.Log10(step) - 1e-9))
	}
	if dec < 0 {
		dec = 0
	}
	if dec > 6 {
		dec = 6
	}
	s := strconv.FormatFloat(v, 'f', dec, 64)
	if s == "-0" {
		s = "0"
	}
	return s
}

// niceTicks returns evenly spaced "nice" (1/2/5 x 10^k) ticks covering
// [lo,hi] using about target intervals. Degenerate ranges widen to a unit.
func niceTicks(lo, hi float64, target int) []float64 {
	if target < 1 {
		target = 1
	}
	if hi < lo {
		lo, hi = hi, lo
	}
	if hi-lo < 1e-12 {
		hi = lo + 1
	}
	raw := (hi - lo) / float64(target)
	mag := math.Pow(10, math.Floor(math.Log10(raw)))
	step := mag
	for _, m := range []float64{1, 2, 5, 10} {
		step = m * mag
		if raw <= step {
			break
		}
	}
	start := math.Floor(lo/step+1e-9) * step
	end := math.Ceil(hi/step-1e-9) * step
	var out []float64
	for v := start; v <= end+step*1e-6; v += step {
		out = append(out, math.Round(v/step)*step)
	}
	return out
}

// statTile draws a labelled value tile; accent colours the left rule.
func (c *canvas) statTile(x, y, w, h int, label, value string, accent color.RGBA) {
	c.rect(x, y, w, h, c.pal.panel)
	c.strokeRect(x, y, w, h, c.pal.grid)
	c.rect(x, y, 4, h, accent)
	c.text(x+14, y+8, c.truncate(fontSans, 12, label, w-24), fontSans, 12, c.pal.muted)
	c.text(x+14, y+26, c.truncate(fontBold, 20, value, w-24), fontBold, 20, c.pal.ink)
}

// chip draws a rounded-less label chip and returns its width.
func (c *canvas) chip(x, y int, s string, bg, fg color.RGBA) int {
	w := c.measure(fontBold, 12, s) + 14
	c.rect(x, y, w, 20, bg)
	c.text(x+7, y+3, s, fontBold, 12, fg)
	return w
}

// legendItem is one swatch+label legend entry.
type legendItem struct {
	Label string
	Color color.RGBA
}

// legend draws entries left to right wrapping at maxX; returns height used.
func (c *canvas) legend(x, y, maxX int, items []legendItem) int {
	cx, cy := x, y
	for _, it := range items {
		w := 16 + c.measure(fontSans, 12, it.Label) + 18
		if cx+w > maxX && cx > x {
			cx, cy = x, cy+22
		}
		c.rect(cx, cy+2, 12, 12, it.Color)
		c.text(cx+18, cy, it.Label, fontSans, 12, c.pal.ink)
		cx += w
	}
	return cy + 22 - y
}

// tableGrid draws row/column rules for a table with given column widths.
func (c *canvas) tableGrid(x, y int, colW []int, rowH, rows int) {
	total := 0
	for _, w := range colW {
		total += w
	}
	for r := 0; r <= rows; r++ {
		c.rect(x, y+r*rowH, total+1, 1, c.pal.grid)
	}
	cx := x
	for i := 0; i <= len(colW); i++ {
		c.rect(cx, y, 1, rows*rowH+1, c.pal.grid)
		if i < len(colW) {
			cx += colW[i]
		}
	}
}

// drawTitleBar draws brand, the render title and the generated badge.
func (c *canvas) drawTitleBar(title string) {
	w := c.img.Bounds().Dx()
	c.rect(0, 0, w, titleH, c.pal.panel)
	c.rect(0, titleH-1, w, 1, c.pal.grid)
	bx := frameGut
	bx += c.text(bx, 11, brandText, fontBold, 15, c.pal.accent) + 14
	badgeW := c.measure(fontBold, 12, badgeText) + 16
	c.strokeRect(w-frameGut-badgeW, 9, badgeW, 22, c.pal.muted)
	c.text(w-frameGut-badgeW+8, 13, badgeText, fontBold, 12, c.pal.muted)
	c.text(bx, 12, c.truncate(fontSans, 14, title, w-bx-badgeW-2*frameGut), fontSans, 14, c.pal.ink)
}

// drawFooter always draws the provenance line (FooterText) plus extra detail.
func (c *canvas) drawFooter(extra string) {
	b := c.img.Bounds()
	y := b.Dy() - footerH
	c.rect(0, y, b.Dx(), footerH, c.pal.panel)
	c.rect(0, y, b.Dx(), 1, c.pal.grid)
	c.text(frameGut, y+8, FooterText, fontBold, 12, c.pal.ink)
	if extra = strings.TrimSpace(extra); extra != "" {
		c.text(frameGut, y+25, c.truncate(fontSans, 12, extra, b.Dx()-2*frameGut), fontSans, 12, c.pal.muted)
	}
}

// frame describes one evidence render; renderFrame enforces chrome and caps.
type frame struct {
	Title      string
	Provenance string
	// BodyHeight returns the content height for the given plotted-row budget.
	BodyHeight func(rows int) int
	// Draw paints content into body (below title bar, above footer).
	Draw func(c *canvas, body image.Rectangle, rows int)
}

// renderFrame draws chrome (title bar + mandatory footer), clamps size, and
// halves the row budget until the PNG fits MaxPNGBytes.
func renderFrame(o Opts, f frame) ([]byte, int, int, error) {
	w := o.width()
	rows := o.maxRows()
	for {
		if !o.Deadline.IsZero() && time.Now().After(o.Deadline) {
			return nil, 0, 0, ErrRenderTimeout
		}
		h := titleH + f.BodyHeight(rows) + footerH
		if h > maxRenderHeight {
			h = maxRenderHeight
		}
		if h < titleH+footerH+1 {
			h = titleH + footerH + 1
		}
		c := newCanvas(w, h, paletteFor(o.Dark))
		f.Draw(c, image.Rect(0, titleH, w, h-footerH), rows)
		// chrome last so content can never cover it
		c.rect(0, 0, w, titleH, c.pal.paper)
		c.drawTitleBar(f.Title)
		c.rect(0, h-footerH, w, footerH, c.pal.paper)
		prov := f.Provenance
		if o.SourceRef != "" {
			prov = strings.TrimSpace(prov + "  |  ref " + o.SourceRef)
		}
		if c.escaped {
			prov = strings.TrimSpace(prov + "  " + escapedFooterNote)
		}
		c.drawFooter(prov)
		c.close()
		data, err := encodePNG(c.img, MaxPNGBytes, func() bool {
			if rows <= 1 {
				return false
			}
			rows /= 2
			return true
		})
		if err == errShrink {
			continue
		}
		if err == nil {
			data = rendermark.Embed(data, "generated evidence render; not a browser screenshot; title="+f.Title+"; ref="+o.SourceRef)
		}
		return data, w, h, err
	}
}

var errShrink = fmt.Errorf("preview: png over cap, shrinking")

// encodePNG encodes img deterministically. When over cap it calls shrink; if
// shrink reports true the caller should redraw (errShrink is returned).
func encodePNG(img image.Image, cap int, shrink func() bool) ([]byte, error) {
	var buf bytes.Buffer
	enc := png.Encoder{CompressionLevel: png.BestSpeed}
	if err := enc.Encode(&buf, img); err != nil {
		return nil, err
	}
	if cap > 0 && buf.Len() > cap {
		if shrink != nil && shrink() {
			return nil, errShrink
		}
		return nil, fmt.Errorf("preview: png %d bytes exceeds cap %d", buf.Len(), cap)
	}
	return buf.Bytes(), nil
}
